export const about = "About";
export const skills = "Skills";
export const resume = "Resume";
export const personalInfo = "Personal Information";
export const experience = "Experience";
export const education = "Education & Qualification."
export const krishnaResume = "Krishna Chivte's Resume.";
export const techStack = "Tech Stack.";
export const profiles = "Coding Profiles.";
export const certificates = "Certificates.";